# Analysis PD Male vs PD Female and all PD patients

In [4]:
import sys
sys.path.append('/mnt/0A2AAC152AABFBB7/CGE/luxgiant-clinical')
import luxgiant_clinical.ClinicalReport as lxc

In [5]:
import pandas as pd

In [7]:
df = pd.read_csv('/mnt/0A2AAC152AABFBB7/CGE/luxgiant-clinical/data/cleaned_file.csv', index_col=0, low_memory=False)
df_cases = df[df['Status']=='Patient'].reset_index(drop=True)
df_cases

,hyonoff,Status,hoehn_and_yahr_staging,age_at_onset,years_of_education,PD_duration,pdsl,agecat_1,agecat_2,agecatmd,...,functional_impact_of_fluct,complexity_of_motor_fluctu,painful_off_state_dystonia,total_score_part_iv,total_score_mds_updrs_part8,mds_updrs_complete,hy_hoehn_and_yahr_complete,dna_storage,date_stored,dna_complete
0,NaN,Patient,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Incomplete,Incomplete,Yes,2020-01-02,Complete
1,Off,Patient,2 - Bilateral disease without impairment of ba...,42.0,3.0,3.0,<=5,<50,>=40,21-49,...,0: Normal: No fluctuations or No impact by f...,0: Normal: No motor fluctuations.,0: Normal: No dystonia OR NO OFF TIME.,0.0,48.0,Unverified,Unverified,Yes,NaN,Unverified
2,On,Patient,1 - Unilateral disease,NaN,17.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,62.0,Unverified,Unverified,Yes,NaN,Unverified
3,On,Patient,2 - Bilateral disease without impairment of ba...,16.0,15.0,19.0,>5,<50,<40,<21,...,3: Moderate: Fluctuations impact on the perf...,2: Mild: OFF times are predictable most of th...,0: Normal: No dystonia OR NO OFF TIME.,6.0,36.0,Unverified,Unverified,Yes,NaN,Unverified
4,On,Patient,1 - Unilateral disease,31.0,15.0,9.0,>5,<50,<40,21-49,...,NaN,NaN,NaN,NaN,14.0,Unverified,Unverified,Yes,NaN,Unverified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7929,NaN,Patient,2 - Bilateral disease without impairment of ba...,67.0,0.0,3.0,<=5,>=50,>=40,>60,...,NaN,NaN,NaN,NaN,NaN,Incomplete,Complete,Yes,2023-11-03,Complete
7930,NaN,Patient,1 - Unilateral disease,47.0,NaN,10.0,>5,<50,>=40,21-49,...,NaN,NaN,NaN,NaN,NaN,Incomplete,Complete,Yes,2023-11-08,Complete
7931,NaN,Patient,1 - Unilateral disease,60.0,NaN,8.0,>5,>=50,>=40,>60,...,NaN,NaN,NaN,NaN,NaN,Incomplete,Complete,Yes,2023-11-10,Complete
7932,NaN,Patient,2 - Bilateral disease without impairment of ba...,61.0,10.0,5.0,>5,>=50,>=40,>60,...,NaN,NaN,NaN,NaN,NaN,Incomplete,Complete,Yes,2023-11-15,Complete
7933,NaN,Patient,2 - Bilateral disease without impairment of ba...,59.0,NaN,5.0,>5,>=50,>=40,50-60,...,NaN,NaN,NaN,NaN,NaN,Incomplete,Complete,Yes,2023-11-17,Complete

In [8]:
variables_4_patients = [
    'age', 'age_at_onset', 'bmi_comp', 'total_score_for_moca', 'PD_duration', 'years_of_education', 'total_score_for_bdi'
]
lxc.descriptive_analytics(df_cases[variables_4_patients])

,age,age_at_onset,bmi_comp,total_score_for_moca,PD_duration,years_of_education,total_score_for_bdi
mean,60.498,54.237,24.254,23.675,6.152,11.425,9.988
stddev,11.320,11.813,3.639,5.533,4.966,5.307,6.769
min,18.000,10.000,12.484,0.000,0.000,0.000,0.000
max,91.000,90.000,40.375,30.000,31.000,48.000,55.000
first_Q,53.000,46.000,21.907,21.000,2.000,9.000,5.000
median,61.000,55.000,24.142,25.000,5.000,12.000,9.000
third_Q,69.000,63.000,26.446,28.000,9.000,15.000,13.000

In [9]:
# Splitting the file by 'sex'
lxc.descriptive_analytics_by_group(df_data=df_cases, variables=variables_4_patients, group_var='sex')

sex                              Female       Male
age                  mean     59.686051  60.886007
                     std      11.043762  11.431398
                     min      18.000000  18.000000
                     max      90.000000  91.000000
                     first_Q  53.000000  53.000000
                     median   60.000000  62.000000
                     third_Q  67.000000  69.000000
age_at_onset         mean     53.457102  54.608007
                     std      11.505298  11.940168
                     min      12.000000  10.000000
                     max      85.000000  90.000000
                     first_Q  46.000000  47.000000
                     median   54.000000  55.000000
                     third_Q  61.416667  63.000000
bmi_comp             mean     24.167067  24.290859
                     std       3.996703   3.468445
                     min      12.484005  13.771948
                     max      39.555556  40.374610
                     first_Q  21.366869  22.100290
                     median   23.920627  24.221453
                     third_Q  26.498797  26.421240
total_score_for_moca mean     22.782416  24.055914
                     std       6.198874   5.178564
                     min       0.000000   0.000000
                     max      30.000000  30.000000
                     first_Q  20.000000  22.000000
                     median   24.000000  25.000000
                     third_Q  27.000000  28.000000
PD_duration          mean      6.099993   6.176481
                     std       4.907312   4.993856
                     min       0.000000   0.000000
                     max      31.000000  31.000000
                     first_Q   2.000000   2.000000
                     median    5.000000   5.000000
                     third_Q   9.000000   9.000000
years_of_education   mean      9.632064  12.287982
                     std       5.765649   4.839875
                     min       0.000000   0.000000
                     max      30.000000  48.000000
                     first_Q   5.000000  10.000000
                     median   10.000000  12.000000
                     third_Q  15.000000  15.000000
total_score_for_bdi  mean     10.438727   9.773266
                     std       6.858138   6.716982
                     min       0.000000   0.000000
                     max      55.000000  47.000000
                     first_Q   6.000000   5.000000
                     median    9.000000   8.000000
                     third_Q  14.000000  13.000000

In [10]:
lxc.t_test_by_group(df_data=df_cases, variables=variables_4_patients, group_var='sex')

,age,age_at_onset,bmi_comp,total_score_for_moca,PD_duration,years_of_education,total_score_for_bdi
t_stat,4.408110,3.936721,1.302473,7.708807e+00,0.622067,2.068544e+01,-3.517196
p_val,0.000011,0.000083,0.192798,1.506699e-14,0.533917,1.916370e-92,0.000439

In [11]:
lxc.mann_whitney_by_groups(df_data=df_cases, variables=variables_4_patients, group_var='sex')

,age,age_at_onset,bmi_comp,total_score_for_moca,PD_duration,years_of_education,total_score_for_bdi
u_stat,7.278170e+06,6.441112e+06,5.260400e+06,3.270978e+06,6.134128e+06,7.523388e+06,3.500299e+06
p_val,1.375313e-06,4.127430e-05,7.877597e-03,8.134692e-11,6.474314e-01,1.788440e-77,8.617075e-05

In [12]:
crosstab_vars = [
    'zone_of_origin', 'education_level', 'agecat_1', 'agecat_2', 'pdsl', 'handedness', 'work', 'reason', 
    'nature_of_work___1', 'nature_of_work___2', 'nature_of_work___3', 'over_your_lifetime_have_yo', 
    'during_your_lifetime_did_y', 'in_your_lifetime_have_you', 'in_your_lifetime_have', 
    'have_you_ever_had_a_head_i', 'l_dopa_carbidopa', 'pramipexole', 'ropinerole', 'rasageline', 
    'selegeline', 'entacapone', 'amantadine', 'apomorphine', 'medical_history_neurologic___7', 
    'medical_history_cancer___1', 'medical_history_cancer___2', 'medical_history_cancer___3', 
    'medical_history_cancer___4', 'medical_history_metabolic___1', 'medical_history_metabolic___3', 
    'medical_history_metabolic___4', 'medical_history_cardiovasc___1', 'medical_history_cardiovasc___2', 
    'medical_history_cardiovasc___3', 'medical_history_psychologi___1', 'medical_history_psychologi___3', 
    'family_member_diagnosed_wi', 'family_member_diagnosed_wi_2', 'family_member_diagnosed', 
    'ct_head', 'mri_brain_imaging', 'datscan', 'f_dopa_pet', 'pd_surgical_treatment', 'dbs_done'
]

In [13]:
lxc.chi_squared_tests(df_data=df_cases, variables=crosstab_vars, group_var='sex')

zone_of_origin sex             Female  Male
zone_of_origin
Central Zone       237   416
Eastern Zone       298   696
Northern Zone      277   608
Southern Zone     1409  2957
Western Zone       271   561
education_level sex              Female  Male
education_level
1 to 7              380   453
8 to 12             913  1944
Above 12            733  2380
Illiterate          363   199
agecat_1 sex       Female  Male
agecat_1
<50          858  1591
>=50        1545  3473
agecat_2 sex       Female  Male
agecat_2
<40          268   565
>=40        2135  4499
pdsl sex   Female  Male
pdsl
<=5     1109  2346
>5      1297  2720
handedness sex               Female  Male
handedness
Ambidexterity          6    10
Left-handedness       43    95
Right-handedness    2498  5250
work sex   Female  Male
work
No      1498  2328
Yes      943  2816
reason sex             Female  Male
reason
PD related         413  1036
not PD related     684  2209
nature_of_work___1 sex                 Female  Male
nature_of_work___1
Checked                246   906
Unchecked             2305  4461
nature_of_work___2 sex                 Female  Male
nature_of_work___2
Checked                 12    58
Unchecked             2539  5309
nature_of_work___3 sex                 Female  Male
nature_of_work___3
Checked                  3    28
Unchecked             2548  5339
over_your_lifetime_have_yo sex                         Female  Male
over_your_lifetime_have_yo
Dont Know                       35    71
No                            2123  4097
Refused                          0     2
Yes                            382  1154
during_your_lifetime_did_y sex                         Female  Male
during_your_lifetime_did_y
Dont Know                       34    88
No                            2107  4093
Refused                          0     2
Yes                            396  1139
in_your_lifetime_have_you sex                        Female  Male
in_your_lifetime_have_you
Dont Know                      38    80
No                           2468  4364
Refused                         0     8
Yes                            33   869
in_your_lifetime_have sex                    Female  Male
in_your_lifetime_have
Dont Know                  46   106
No                       1920  3848
Refused                     1     1
Yes                       570  1364
have_you_ever_had_a_head_i sex                         Female  Male
have_you_ever_had_a_head_i
Dont Know                       69   154
No                            2280  4635
Possibly                        47   120
Refused                          4     5
Yes                            138   408
l_dopa_carbidopa sex               Female  Male
l_dopa_carbidopa
No                   226   446
Yes                 1991  4183
pramipexole sex          Female  Male
pramipexole
No              773  1622
Yes             919  2019
ropinerole sex         Female  Male
ropinerole
No            1251  2655
Yes            182   396
rasageline sex         Female  Male
rasageline
No            1138  2441
Yes            297   632
selegeline sex         Female  Male
selegeline
No            1307  2780
Yes             16    43
entacapone sex         Female  Male
entacapone
No            1221  2569
Yes            124   298
amantadine sex         Female  Male
amantadine
No            1031  2186
Yes            432   860
apomorphine sex          Female  Male
apomorphine
No             1273  2745
Yes               6     2
medical_history_neurologic___7 sex                             Female  Male
medical_history_neurologic___7
Checked                             23    50
Unchecked                         2528  5317
medical_history_cancer___1 sex                         Female  Male
medical_history_cancer___1
Checked                          0     4
Unchecked                     2551  5363
medical_history_cancer___2 sex                         Female  Male
medical_history_cancer___2
Checked                          1    12
Unchecked                     2550  5355
medical_history_cancer___3 sex                         Female  Male
medical_history_cancer___3
Checked                         32    31
Unchecked                     2519  5336
medical_history_cancer___4 sex                         Female  Male
medical_history_cancer___4
Checked                       2440  5184
Unchecked                      111   183
medical_history_metabolic___1 sex                            Female  Male
medical_history_metabolic___1
Checked                           427  1145
Unchecked                        2124  4222
medical_history_metabolic___3 sex                            Female  Male
medical_history_metabolic___3
Checked                           117   185
Unchecked                        2434  5182
medical_history_metabolic___4 sex                            Female  Male
medical_history_metabolic___4
Checked                           142    96
Unchecked                        2409  5271
medical_history_cardiovasc___1 sex                             Female  Male
medical_history_cardiovasc___1
Checked                             29   156
Unchecked                         2522  5211
medical_history_cardiovasc___2 sex                             Female  Male
medical_history_cardiovasc___2
Checked                            678  1420
Unchecked                         1873  3947
medical_history_cardiovasc___3 sex                             Female  Male
medical_history_cardiovasc___3
Checked                             31   149
Unchecked                         2520  5218
medical_history_psychologi___1 sex                             Female  Male
medical_history_psychologi___1
Checked                            123   279
Unchecked                         2428  5088
medical_history_psychologi___3 sex                             Female  Male
medical_history_psychologi___3
Checked                            180   241
Unchecked                         2371  5126
family_member_diagnosed_wi sex                         Female  Male
family_member_diagnosed_wi
No                            2248  4699
Yes                            223   486
family_member_diagnosed_wi_2 sex                           Female  Male
family_member_diagnosed_wi_2
No                              2184  4531
Yes                              181   442
family_member_diagnosed sex                      Female  Male
family_member_diagnosed
No                         2310  4874
Yes                          38    86
ct_head sex      Female  Male
ct_head
No         1643  3528
Yes         281   595
mri_brain_imaging sex                Female  Male
mri_brain_imaging
No                   1115  2270
Yes                   806  1851
datscan sex      Female  Male
datscan
No         1757  3804
Yes          65   173
f_dopa_pet sex         Female  Male
f_dopa_pet
No            1688  3658
Yes             40   103
pd_surgical_treatment sex                    Female  Male
pd_surgical_treatment
No                       1641  3531
Yes                       107   299
dbs_done sex       Female  Male
dbs_done
No          1623  3473
Yes          115   301

,zone_of_origin,education_level,agecat_1,agecat_2,pdsl,handedness,work,reason,nature_of_work___1,nature_of_work___2,...,medical_history_psychologi___3,family_member_diagnosed_wi,family_member_diagnosed_wi_2,family_member_diagnosed,ct_head,mri_brain_imaging,datscan,f_dopa_pet,pd_surgical_treatment,dbs_done
chi2,7.639603,4.437409e+02,13.398247,0.0,0.022453,0.276223,1.712612e+02,11.816711,7.227573e+01,6.669419,...,22.102348,0.202184,2.988144,0.067570,0.019482,4.536974,1.750282,0.679465,4.805710,2.957200
p_val,0.105709,7.402294e-96,0.000252,1.0,0.880890,0.871001,3.923859e-39,0.000587,1.871350e-17,0.009808,...,0.000003,0.652964,0.083876,0.794909,0.888994,0.033170,0.185841,0.409771,0.028366,0.085496
dof,4.000000,3.000000e+00,1.000000,1.0,1.000000,2.000000,1.000000e+00,1.000000,1.000000e+00,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

Let us consider only the patients. Given certain tests, let us check if there are differences by sex.

In [14]:
conditions = {
    'ct_head'          : ['ct_result___1'],
    'mri_brain_imaging': ['mri_result___1'],
    'datscan'          : ['datscan_result___1'],
    'f_dopa_pet'       : ['f_dopa_pet_result___1']
}

In [15]:
lxc.chi_squared_conditioned(
    df_data      =df_cases,
    conditionants=conditions,
    condition    ='Yes',
    group_var    ='sex'
)

ct_result___1 sex            Female  Male
ct_result___1
Checked           213   460
Unchecked          68   135
mri_result___1 sex             Female  Male
mri_result___1
Checked            518  1169
Unchecked          288   682
datscan_result___1 sex                 Female  Male
datscan_result___1
Checked                  2     7
Unchecked               63   166
f_dopa_pet_result___1 sex                    Female  Male
f_dopa_pet_result___1
Checked                     4     5
Unchecked                  36    98

           Condition               Variable      chi2     p_val  dof
0            ct_head          ct_result___1  0.167038  0.682758  1.0
1  mri_brain_imaging         mri_result___1  0.253953  0.614305  1.0
2            datscan     datscan_result___1       0.0       1.0  1.0
3         f_dopa_pet  f_dopa_pet_result___1  0.568125  0.451005  1.0

In [16]:
crosstab_vars_1 = [
    'psychiatric_symptoms_type___1', 'psychiatric_symptoms_type___2', 'psychiatric_symptoms_type___3',
    'initial_symptom_s___1', 'initial_symptom_s___2', 'inmotnonmot'
]

In [17]:
lxc.chi_squared_tests(df_data=df_cases, variables=crosstab_vars_1, group_var='sex')

psychiatric_symptoms_type___1 sex                            Female  Male
psychiatric_symptoms_type___1
Checked                            24    35
Unchecked                        2527  5332
psychiatric_symptoms_type___2 sex                            Female  Male
psychiatric_symptoms_type___2
Checked                             4    15
Unchecked                        2547  5352
psychiatric_symptoms_type___3 sex                            Female  Male
psychiatric_symptoms_type___3
Checked                           135   204
Unchecked                        2416  5163
initial_symptom_s___1 sex                    Female  Male
initial_symptom_s___1
Checked                  2278  4802
Unchecked                 273   565
initial_symptom_s___2 sex                    Female  Male
initial_symptom_s___2
Checked                   173   344
Unchecked                2378  5023
inmotnonmot sex          Female  Male
inmotnonmot
Checked         108   230
Unchecked      2443  5137

,psychiatric_symptoms_type___1,psychiatric_symptoms_type___2,psychiatric_symptoms_type___3,initial_symptom_s___1,initial_symptom_s___2,inmotnonmot
chi2,1.577522,0.635101,9.020111,0.038667,0.333708,0.002219
p_val,0.209118,0.425491,0.002670,0.844109,0.563484,0.962433
dof,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [18]:
lxc.fisher_exact_test(df_data=df_cases, variables=crosstab_vars_1, group_var='sex')

,psychiatric_symptoms_type___1,psychiatric_symptoms_type___2,psychiatric_symptoms_type___3,initial_symptom_s___1,initial_symptom_s___2,inmotnonmot
fisher,1.446865,0.560346,1.414193,0.981787,1.062280,0.987375
p_val,0.164328,0.460833,0.002918,0.814654,0.527271,0.952598

In [19]:
crosstab_vars_2 = [
    'initial_motor_symptom_s___1', 'initial_motor_symptom_s___2', 'initial_motor_symptom_s___3', 
    'initial_motor_symptom_s___4', 'initial_motor_symptom_s___5', 'initial_motor_symptom_s___6', 
    'initial_motor_symptom_s___7', 'initial_motor_symptom_s___8', 'initial_motor_symptom_s___9', 
    'initial_motor_symptom_s___10', 'initial_motor_symptom_s___11', 'initial_motor_symptom_s___12', 
    'initial_motor_symptom_s___13', 'initial_motor_symptom_s___14', 'initial_motor_symptom_s___15', 
    'initial_motor_symptom_s___16', 'initial_motor_symptom_s___17'
]
lxc.chi_squared_tests(df_data=df_cases, variables=crosstab_vars_2, group_var='sex')

initial_motor_symptom_s___1 sex                          Female  Male
initial_motor_symptom_s___1
Checked                          12    23
Unchecked                      2539  5344
initial_motor_symptom_s___2 sex                          Female  Male
initial_motor_symptom_s___2
Checked                        1514  3215
Unchecked                      1037  2152
initial_motor_symptom_s___3 sex                          Female  Male
initial_motor_symptom_s___3
Checked                         617  1338
Unchecked                      1934  4029
initial_motor_symptom_s___4 sex                          Female  Male
initial_motor_symptom_s___4
Checked                         181   305
Unchecked                      2370  5062
initial_motor_symptom_s___5 sex                          Female  Male
initial_motor_symptom_s___5
Checked                          56   151
Unchecked                      2495  5216
initial_motor_symptom_s___6 sex                          Female  Male
initial_motor_symptom_s___6
Checked                          31    65
Unchecked                      2520  5302
initial_motor_symptom_s___7 sex                          Female  Male
initial_motor_symptom_s___7
Checked                         104   230
Unchecked                      2447  5137
initial_motor_symptom_s___8 sex                          Female  Male
initial_motor_symptom_s___8
Checked                         285   622
Unchecked                      2266  4745
initial_motor_symptom_s___9 sex                          Female  Male
initial_motor_symptom_s___9
Checked                         119   356
Unchecked                      2432  5011
initial_motor_symptom_s___10 sex                           Female  Male
initial_motor_symptom_s___10
Checked                          149   272
Unchecked                       2402  5095
initial_motor_symptom_s___11 sex                           Female  Male
initial_motor_symptom_s___11
Checked                          512  1080
Unchecked                       2039  4287
initial_motor_symptom_s___12 sex                           Female  Male
initial_motor_symptom_s___12
Checked                         1004  2045
Unchecked                       1547  3322
initial_motor_symptom_s___13 sex                           Female  Male
initial_motor_symptom_s___13
Checked                          811  1603
Unchecked                       1740  3764
initial_motor_symptom_s___14 sex                           Female  Male
initial_motor_symptom_s___14
Checked                          177   373
Unchecked                       2374  4994
initial_motor_symptom_s___15 sex                           Female  Male
initial_motor_symptom_s___15
Checked                           96   171
Unchecked                       2455  5196
initial_motor_symptom_s___16 sex                           Female  Male
initial_motor_symptom_s___16
Checked                          368   781
Unchecked                       2183  4586
initial_motor_symptom_s___17 sex                           Female  Male
initial_motor_symptom_s___17
Checked                           58   100
Unchecked                       2493  5267

,initial_motor_symptom_s___1,initial_motor_symptom_s___2,initial_motor_symptom_s___3,initial_motor_symptom_s___4,initial_motor_symptom_s___5,initial_motor_symptom_s___6,initial_motor_symptom_s___7,initial_motor_symptom_s___8,initial_motor_symptom_s___9,initial_motor_symptom_s___10,initial_motor_symptom_s___11,initial_motor_symptom_s___12,initial_motor_symptom_s___13,initial_motor_symptom_s___14,initial_motor_symptom_s___15,initial_motor_symptom_s___16,initial_motor_symptom_s___17
chi2,0.006582,0.198071,0.474892,5.744484,2.359021,0.0,0.138199,0.257091,11.532923,1.900829,0.000594,1.095759,2.929418,0.0,1.594662,0.013185,1.286604
p_val,0.935340,0.656282,0.490745,0.016541,0.124560,1.0,0.710078,0.612126,0.000684,0.167986,0.980551,0.295199,0.086979,1.0,0.206661,0.908583,0.256675
dof,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.000000,1.000000

In [20]:
crosstab_vars_3 = [
    'initial_non_motor_symptom___1', 'initial_non_motor_symptom___2', 'initial_non_motor_symptom___3', 
    'initial_non_motor_symptom___4', 'initial_non_motor_symptom___5', 'initial_non_motor_symptom___6', 
    'initial_non_motor_symptom___7', 'initial_non_motor_symptom___8', 'initial_non_motor_symptom___9', 
    'initial_non_motor_symptom___10', 'initial_non_motor_symptom___11', 'initial_non_motor_symptom___12', 
    'initial_non_motor_symptom___13', 'initial_non_motor_symptom___14', 'initial_non_motor_symptom___15', 
    'initial_non_motor_symptom___16', 'initial_non_motor_symptom___17', 'initial_non_motor_symptom___18', 
    'initial_non_motor_symptom___19', 'initial_non_motor_symptom___20', 'initial_non_motor_symptom___21'
]
lxc.chi_squared_tests(df_data=df_cases, variables=crosstab_vars_3, group_var='sex')

initial_non_motor_symptom___1 sex                            Female  Male
initial_non_motor_symptom___1
Checked                          1163  2418
Unchecked                        1388  2949
initial_non_motor_symptom___2 sex                            Female  Male
initial_non_motor_symptom___2
Checked                            73   220
Unchecked                        2478  5147
initial_non_motor_symptom___3 sex                            Female  Male
initial_non_motor_symptom___3
Checked                            43    77
Unchecked                        2508  5290
initial_non_motor_symptom___4 sex                            Female  Male
initial_non_motor_symptom___4
Checked                           259   573
Unchecked                        2292  4794
initial_non_motor_symptom___5 sex                            Female  Male
initial_non_motor_symptom___5
Checked                            83   126
Unchecked                        2468  5241
initial_non_motor_symptom___6 sex                            Female  Male
initial_non_motor_symptom___6
Checked                            50    70
Unchecked                        2501  5297
initial_non_motor_symptom___7 sex                            Female  Male
initial_non_motor_symptom___7
Checked                            34    91
Unchecked                        2517  5276
initial_non_motor_symptom___8 sex                            Female  Male
initial_non_motor_symptom___8
Checked                           195   403
Unchecked                        2356  4964
initial_non_motor_symptom___9 sex                            Female  Male
initial_non_motor_symptom___9
Checked                            29    87
Unchecked                        2522  5280
initial_non_motor_symptom___10 sex                             Female  Male
initial_non_motor_symptom___10
Checked                             42   115
Unchecked                         2509  5252
initial_non_motor_symptom___11 sex                             Female  Male
initial_non_motor_symptom___11
Checked                             21    63
Unchecked                         2530  5304
initial_non_motor_symptom___12 sex                             Female  Male
initial_non_motor_symptom___12
Checked                              6     8
Unchecked                         2545  5359
initial_non_motor_symptom___13 sex                             Female  Male
initial_non_motor_symptom___13
Checked                             36    45
Unchecked                         2515  5322
initial_non_motor_symptom___14 sex                             Female  Male
initial_non_motor_symptom___14
Checked                             20    42
Unchecked                         2531  5325
initial_non_motor_symptom___15 sex                             Female  Male
initial_non_motor_symptom___15
Checked                             14    27
Unchecked                         2537  5340
initial_non_motor_symptom___16 sex                             Female  Male
initial_non_motor_symptom___16
Checked                              8    17
Unchecked                         2543  5350
initial_non_motor_symptom___17 sex                             Female  Male
initial_non_motor_symptom___17
Checked                              3    16
Unchecked                         2548  5351
initial_non_motor_symptom___18 sex                             Female  Male
initial_non_motor_symptom___18
Checked                            417   930
Unchecked                         2134  4437
initial_non_motor_symptom___19 sex                             Female  Male
initial_non_motor_symptom___19
Checked                              8    27
Unchecked                         2543  5340
initial_non_motor_symptom___20 sex                             Female  Male
initial_non_motor_symptom___20
Checked                            159   301
Unchecked                         2392  5066
initial_non_motor_symptom___21 sex                             Female  Male
initial_non_motor_symptom___21
Checked                             50    96
Unchecked                         2501  5271

,initial_non_motor_symptom___1,initial_non_motor_symptom___2,initial_non_motor_symptom___3,initial_non_motor_symptom___4,initial_non_motor_symptom___5,initial_non_motor_symptom___6,initial_non_motor_symptom___7,initial_non_motor_symptom___8,initial_non_motor_symptom___9,initial_non_motor_symptom___10,...,initial_non_motor_symptom___12,initial_non_motor_symptom___13,initial_non_motor_symptom___14,initial_non_motor_symptom___15,initial_non_motor_symptom___16,initial_non_motor_symptom___17,initial_non_motor_symptom___18,initial_non_motor_symptom___19,initial_non_motor_symptom___20,initial_non_motor_symptom___21
chi2,0.180094,7.087687,0.570970,0.449746,5.175372,4.551936,1.240130,0.027981,2.482981,1.943603,...,0.320831,5.050813,0.0,0.009489,0.0,1.660103,1.111585,1.012857,1.120899,0.193702
p_val,0.671293,0.007762,0.449874,0.502456,0.022909,0.032882,0.265446,0.867153,0.115084,0.163278,...,0.571109,0.024614,1.0,0.922398,1.0,0.197589,0.291738,0.314219,0.289725,0.659853
dof,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.0,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000

In [21]:
crosstab_vars_4 = [
    'current_motor_symptom_s___1', 'current_motor_symptom_s___2', 'current_motor_symptom_s___3', 
    'current_motor_symptom_s___4', 'current_motor_symptom_s___5', 'current_motor_symptom_s___6',
    'current_motor_symptom_s___7', 'current_motor_symptom_s___8', 'current_motor_symptom_s___9',
    'current_motor_symptom_s___10', 'current_motor_symptom_s___12', 'current_motor_symptom_s___13',
    'current_motor_symptom_s___14', 'current_motor_symptom_s___15', 'current_motor_symptom_s___16',
    'current_motor_symptom_s___17', 'current_motor_symptom_s___18', 'current_motor_symptom_s___19',
    'current_motor_symptom_s___20'
]
lxc.chi_squared_tests(df_data=df_cases, variables=crosstab_vars_4, group_var='sex')

current_motor_symptom_s___1 sex                          Female  Male
current_motor_symptom_s___1
Checked                          39    66
Unchecked                      2512  5301
current_motor_symptom_s___2 sex                          Female  Male
current_motor_symptom_s___2
Checked                        1608  3502
Unchecked                       943  1865
current_motor_symptom_s___3 sex                          Female  Male
current_motor_symptom_s___3
Checked                         973  2097
Unchecked                      1578  3270
current_motor_symptom_s___4 sex                          Female  Male
current_motor_symptom_s___4
Checked                        1430  3076
Unchecked                      1121  2291
current_motor_symptom_s___5 sex                          Female  Male
current_motor_symptom_s___5
Checked                         715  1685
Unchecked                      1836  3682
current_motor_symptom_s___6 sex                          Female  Male
current_motor_symptom_s___6
Checked                         167   464
Unchecked                      2384  4903
current_motor_symptom_s___7 sex                          Female  Male
current_motor_symptom_s___7
Checked                         468  1263
Unchecked                      2083  4104
current_motor_symptom_s___8 sex                          Female  Male
current_motor_symptom_s___8
Checked                         693  1612
Unchecked                      1858  3755
current_motor_symptom_s___9 sex                          Female  Male
current_motor_symptom_s___9
Checked                         573  1550
Unchecked                      1978  3817
current_motor_symptom_s___10 sex                           Female  Male
current_motor_symptom_s___10
Checked                          775  1609
Unchecked                       1776  3758
current_motor_symptom_s___12 sex                           Female  Male
current_motor_symptom_s___12
Checked                          703  1534
Unchecked                       1848  3833
current_motor_symptom_s___13 sex                           Female  Male
current_motor_symptom_s___13
Checked                         1179  2568
Unchecked                       1372  2799
current_motor_symptom_s___14 sex                           Female  Male
current_motor_symptom_s___14
Checked                         1558  3369
Unchecked                        993  1998
current_motor_symptom_s___15 sex                           Female  Male
current_motor_symptom_s___15
Checked                          945  2017
Unchecked                       1606  3350
current_motor_symptom_s___16 sex                           Female  Male
current_motor_symptom_s___16
Checked                          264   460
Unchecked                       2287  4907
current_motor_symptom_s___17 sex                           Female  Male
current_motor_symptom_s___17
Checked                          393   827
Unchecked                       2158  4540
current_motor_symptom_s___18 sex                           Female  Male
current_motor_symptom_s___18
Checked                          454   773
Unchecked                       2097  4594
current_motor_symptom_s___19 sex                           Female  Male
current_motor_symptom_s___19
Checked                          334   810
Unchecked                       2217  4557
current_motor_symptom_s___20 sex                           Female  Male
current_motor_symptom_s___20
Checked                           22    45
Unchecked                       2529  5322

,current_motor_symptom_s___1,current_motor_symptom_s___2,current_motor_symptom_s___3,current_motor_symptom_s___4,current_motor_symptom_s___5,current_motor_symptom_s___6,current_motor_symptom_s___7,current_motor_symptom_s___8,current_motor_symptom_s___9,current_motor_symptom_s___10,current_motor_symptom_s___12,current_motor_symptom_s___13,current_motor_symptom_s___14,current_motor_symptom_s___15,current_motor_symptom_s___16,current_motor_symptom_s___17,current_motor_symptom_s___18,current_motor_symptom_s___19,current_motor_symptom_s___20
chi2,0.964468,3.615509,0.591673,1.063028,9.123214,10.102853,2.693080e+01,6.761336,3.597390e+01,0.113601,0.845101,1.779878,2.050351,0.190804,6.367413,0.0,14.953476,5.431242,0.0
p_val,0.326064,0.057243,0.441773,0.302526,0.002524,0.001480,2.108717e-07,0.009315,1.999780e-09,0.736081,0.357942,0.182164,0.152171,0.662248,0.011623,1.0,0.000110,0.019780,1.0
dof,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000e+00,1.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.000000,1.0

In [22]:
crosstab_vars_5 = [
    'current_non_motor_symptom___1', 'current_non_motor_symptom___2', 'current_non_motor_symptom___3', 
    'current_non_motor_symptom___4', 'current_non_motor_symptom___5', 'current_non_motor_symptom___6', 
    'current_non_motor_symptom___7', 'current_non_motor_symptom___8', 'current_non_motor_symptom___9', 
    'current_non_motor_symptom___10', 'current_non_motor_symptom___11', 'current_non_motor_symptom___12', 
    'current_non_motor_symptom___13', 'current_non_motor_symptom___14', 'current_non_motor_symptom___15', 
    'current_non_motor_symptom___16', 'current_non_motor_symptom___17', 'current_non_motor_symptom___18', 
    'current_non_motor_symptom___19', 'current_non_motor_symptom___20', 'current_non_motor_symptom___21', 
    'current_non_motor_symptom___22', 'current_non_motor_symptom___23'
]
lxc.chi_squared_tests(df_data=df_cases, variables=crosstab_vars_5, group_var='sex')

current_non_motor_symptom___1 sex                            Female  Male
current_non_motor_symptom___1
Checked                           494   968
Unchecked                        2057  4399
current_non_motor_symptom___2 sex                            Female  Male
current_non_motor_symptom___2
Checked                           232   564
Unchecked                        2319  4803
current_non_motor_symptom___3 sex                            Female  Male
current_non_motor_symptom___3
Checked                            61   116
Unchecked                        2490  5251
current_non_motor_symptom___4 sex                            Female  Male
current_non_motor_symptom___4
Checked                            15    40
Unchecked                        2536  5327
current_non_motor_symptom___5 sex                            Female  Male
current_non_motor_symptom___5
Checked                           344   535
Unchecked                        2207  4832
current_non_motor_symptom___6 sex                            Female  Male
current_non_motor_symptom___6
Checked                           467  1053
Unchecked                        2084  4314
current_non_motor_symptom___7 sex                            Female  Male
current_non_motor_symptom___7
Checked                           131   208
Unchecked                        2420  5159
current_non_motor_symptom___8 sex                            Female  Male
current_non_motor_symptom___8
Checked                            71   136
Unchecked                        2480  5231
current_non_motor_symptom___9 sex                            Female  Male
current_non_motor_symptom___9
Checked                           132   270
Unchecked                        2419  5097
current_non_motor_symptom___10 sex                             Female  Male
current_non_motor_symptom___10
Checked                             83   255
Unchecked                         2468  5112
current_non_motor_symptom___11 sex                             Female  Male
current_non_motor_symptom___11
Checked                            485   885
Unchecked                         2066  4482
current_non_motor_symptom___12 sex                             Female  Male
current_non_motor_symptom___12
Checked                             63   118
Unchecked                         2488  5249
current_non_motor_symptom___13 sex                             Female  Male
current_non_motor_symptom___13
Checked                             93   182
Unchecked                         2458  5185
current_non_motor_symptom___14 sex                             Female  Male
current_non_motor_symptom___14
Checked                             49    84
Unchecked                         2502  5283
current_non_motor_symptom___15 sex                             Female  Male
current_non_motor_symptom___15
Checked                             13    35
Unchecked                         2538  5332
current_non_motor_symptom___16 sex                             Female  Male
current_non_motor_symptom___16
Checked                             75   102
Unchecked                         2476  5265
current_non_motor_symptom___17 sex                             Female  Male
current_non_motor_symptom___17
Checked                             28    90
Unchecked                         2523  5277
current_non_motor_symptom___18 sex                             Female  Male
current_non_motor_symptom___18
Checked                             11    34
Unchecked                         2540  5333
current_non_motor_symptom___19 sex                             Female  Male
current_non_motor_symptom___19
Checked                             38    81
Unchecked                         2513  5286
current_non_motor_symptom___20 sex                             Female  Male
current_non_motor_symptom___20
Checked                            762  1877
Unchecked                         1789  3490
current_non_motor_symptom___21 sex                             Female  Male
current_non_motor_symptom___21
Checked                             19    53
Unchecked                         2532  5314
current_non_motor_symptom___22 sex                             Female  Male
current_non_motor_symptom___22
Checked                            354   872
Unchecked                         2197  4495
current_non_motor_symptom___23 sex                             Female  Male
current_non_motor_symptom___23
Checked                             93   195
Unchecked                         2458  5172

,current_non_motor_symptom___1,current_non_motor_symptom___2,current_non_motor_symptom___3,current_non_motor_symptom___4,current_non_motor_symptom___5,current_non_motor_symptom___6,current_non_motor_symptom___7,current_non_motor_symptom___8,current_non_motor_symptom___9,current_non_motor_symptom___10,...,current_non_motor_symptom___14,current_non_motor_symptom___15,current_non_motor_symptom___16,current_non_motor_symptom___17,current_non_motor_symptom___18,current_non_motor_symptom___19,current_non_motor_symptom___20,current_non_motor_symptom___21,current_non_motor_symptom___22,current_non_motor_symptom___23
chi2,1.940712,3.669564,0.319483,0.413107,21.312168,1.839056,6.391653,0.329619,0.047270,9.127396,...,1.118034,0.370423,8.080706,3.567968,0.919833,0.0,20.029470,0.877138,7.245036,0.0
p_val,0.163591,0.055415,0.571919,0.520397,0.000004,0.175062,0.011466,0.565883,0.827883,0.002518,...,0.290342,0.542774,0.004474,0.058904,0.337519,1.0,0.000008,0.348987,0.007110,1.0
dof,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.000000,1.000000,1.0

In [23]:
conditions_1 = {
    'hyonoff': ['hoehn_and_yahr_staging', 'hystage']
}
lxc.chi_squared_conditioned(
    df_data      =df_cases,
    conditionants=conditions_1,
    condition    ='Off',
    group_var    ='sex'
)

hoehn_and_yahr_staging sex                                                 Female  Male
hoehn_and_yahr_staging
1 - Unilateral disease                                 126   231
1.5 - Unilateral plus axial involvement                 77   158
2 - Bilateral disease without impairment of bal...     277   618
2.5 - Mild bilateral disease with recovery on p...     133   300
3 - Mild to moderate bilateral disease some pos...     182   335
4 - Severe disability - still able to walk or s...      45    85
5 - Wheelchair bound or bedridden unless aided          11    13
hystage sex         Female  Male
hystage
Not severe     795  1642
Severe          56    98

  Condition                Variable      chi2     p_val  dof
0   hyonoff  hoehn_and_yahr_staging  6.642599  0.355167  6.0
1   hyonoff                 hystage   0.75752  0.384106  1.0

In [24]:
variables = [
    'updrs_1_total_score', 'updrs_part_ii_total_score', 'updrs_part_iii_total_score', 'updrs_part_iv_a_total_scor', 
    'updrs_part_iv_b_total_scor', 'updrs_part_iv_c_total_scor', 'total_score_part_i', 'total_score_part_ii', 
    'total_score_part_iii', 'total_score_part_iv', 'total_score_mds_updrs_part8'
]
lxc.conditioned_descriptive_analytics_by_group(
    df_data=df_cases,
    variables=variables,
    group_var='sex',
    condition=('hyonoff', 'Off')
)

sex                                      Female        Male
updrs_1_total_score         mean       1.567213    1.423465
                            std        1.884926    1.794282
                            min        0.000000    0.000000
                            max       10.000000   11.000000
                            first_Q    0.000000    0.000000
...                                         ...         ...
total_score_mds_updrs_part8 min        5.000000    3.000000
                            max      169.000000  153.000000
                            first_Q   32.000000   31.000000
                            median    48.000000   49.000000
                            third_Q   70.000000   69.750000

[77 rows x 2 columns]

In [25]:
lxc.conditioned_mann_whitney_by_groups(
    df_data=df_cases,
    variables=variables,
    group_var='sex',
    condition=('hyonoff', 'Off')    
)

,updrs_1_total_score,updrs_part_ii_total_score,updrs_part_iii_total_score,updrs_part_iv_a_total_scor,updrs_part_iv_b_total_scor,updrs_part_iv_c_total_scor,total_score_part_i,total_score_part_ii,total_score_part_iii,total_score_part_iv,total_score_mds_updrs_part8
u_stat,373929.000000,404054.500000,272146.000000,323770.500000,354025.000000,355093.000000,38369.000000,38590.500000,34515.500000,29922.500000,39841.500000
p_val,0.080295,0.704918,0.385354,0.000041,0.521942,0.671808,0.740129,0.661713,0.843729,0.653461,0.726162

In [26]:
lxc.chi_squared_conditioned(
    df_data      =df_cases,
    conditionants=conditions_1,
    condition    ='On',
    group_var    ='sex'
)

hoehn_and_yahr_staging sex                                                 Female  Male
hoehn_and_yahr_staging
0 - No signs of disease                                 14    27
1 - Unilateral disease                                 204   459
1.5 - Unilateral plus axial involvement                143   266
2 - Bilateral disease without impairment of bal...     441   973
2.5 - Mild bilateral disease with recovery on p...     188   438
3 - Mild to moderate bilateral disease some pos...     210   374
4 - Severe disability - still able to walk or s...      43    85
5 - Wheelchair bound or bedridden unless aided          15    27
hystage sex         Female  Male
hystage
Not severe    1200  2537
Severe          58   112

  Condition                Variable      chi2     p_val  dof
0   hyonoff  hoehn_and_yahr_staging  8.265649  0.309753  7.0
1   hyonoff                 hystage  0.214958  0.642909  1.0

In [ ]:
test = df_cases[df_cases['hyonoff']=='On'].reset_index(drop=True)
test

,hyonoff,Status,hoehn_and_yahr_staging,age_at_onset,years_of_education,PD_duration,pdsl,agecat_1,agecat_2,agecatmd,...,functional_impact_of_fluct,complexity_of_motor_fluctu,painful_off_state_dystonia,total_score_part_iv,total_score_mds_updrs_part8,mds_updrs_complete,hy_hoehn_and_yahr_complete,dna_storage,date_stored,dna_complete
0,On,Patient,NaN,NaN,17.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,62.0,Unverified,Unverified,Yes,NaN,Unverified
1,On,Patient,NaN,16.0,15.0,19.0,>5,<50,<40,<21,...,3: Moderate: Fluctuations impact on the perf...,2: Mild: OFF times are predictable most of th...,0: Normal: No dystonia OR NO OFF TIME.,6.0,36.0,Unverified,Unverified,Yes,NaN,Unverified
2,On,Patient,NaN,31.0,15.0,9.0,>5,<50,<40,21-49,...,NaN,NaN,NaN,NaN,14.0,Unverified,Unverified,Yes,NaN,Unverified
3,On,Patient,NaN,48.0,10.0,12.0,>5,<50,>=40,21-49,...,4: Severe: Fluctuations impact on function t...,3: Moderate: OFF times are predictable some o...,0: Normal: No dystonia OR NO OFF TIME.,8.0,56.0,Unverified,Unverified,Yes,NaN,Unverified
4,On,Patient,NaN,58.0,10.0,7.0,>5,>=50,>=40,50-60,...,3: Moderate: Fluctuations impact on the perf...,2: Mild: OFF times are predictable most of th...,1: Slight: < 25% of time in OFF state.,7.0,41.0,Unverified,Unverified,Yes,NaN,Unverified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4011,On,Patient,NaN,68.0,15.0,5.0,>5,>=50,>=40,>60,...,3: Moderate: Fluctuations impact on the perf...,2: Mild: OFF times are predictable most of th...,0: Normal: No dystonia OR NO OFF TIME.,8.0,59.0,Complete,Complete,Yes,2021-07-10,Complete
4012,On,Patient,NaN,52.0,15.0,9.0,>5,>=50,>=40,50-60,...,2: Mild: Fluctuations impact many activities...,2: Mild: OFF times are predictable most of th...,0: Normal: No dystonia OR NO OFF TIME.,6.0,31.0,Complete,Complete,Yes,2021-07-10,Complete
4013,On,Patient,NaN,49.0,14.0,6.0,>5,<50,>=40,21-49,...,NaN,NaN,NaN,NaN,NaN,Incomplete,Complete,Yes,2021-07-06,Complete
4014,On,Patient,NaN,61.0,NaN,0.0,<=5,>=50,>=40,>60,...,NaN,NaN,NaN,NaN,NaN,Incomplete,Complete,Yes,2022-12-10,Complete
4015,On,Patient,NaN,57.0,NaN,0.0,<=5,>=50,>=40,50-60,...,NaN,NaN,NaN,NaN,NaN,Incomplete,Complete,Yes,2022-12-20,Complete

In [ ]:
test['hoehn_and_yahr_staging'].value_counts(dropna=False)

hoehn_and_yahr_staging
NaN    4016
Name: count, dtype: int64

In [ ]:
df_cases['hoehn_and_yahr_staging'].value_counts(dropna=False)

hoehn_and_yahr_staging
NaN                                                                                        6794
2 - Bilateral disease without impairment of balance                                         462
1 - Unilateral disease                                                                      252
1.5 - Unilateral plus axial involvement                                                     171
2.5 - Mild bilateral disease with recovery on pull test                                     123
3 - Mild to moderate bilateral disease some postural instability physically independent      97
4 - Severe disability - still able to walk or stand unassisted                               20
0 - No signs of disease                                                                       8
5 - Wheelchair bound or bedridden unless aided                                                7
Name: count, dtype: int64