# Analysis PD Male vs PD Female and all PD patients

In [1]:
import sys
sys.path.append('/mnt/0A2AAC152AABFBB7/CGE/luxgiant-clinical')
import luxgiant_clinical.ClinicalReport as lxc

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/mnt/0A2AAC152AABFBB7/CGE/luxgiant-clinical/data/cleaned_file.csv', index_col=0, low_memory=False)
df_cases = df[df['Status']=='Patient'].reset_index(drop=True)
df_cases

,age_at_onset,years_of_education,PD_duration,pdsl,agecat_1,agecat_2,agecatmd,agecent,education2,initial_symptom_s___1,...,functional_impact_of_fluct,complexity_of_motor_fluctu,painful_off_state_dystonia,total_score_part_iv,total_score_mds_updrs_part8,mds_updrs_complete,hy_hoehn_and_yahr_complete,dna_storage,date_stored,dna_complete
0,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,<=12,Unchecked,...,NaN,NaN,NaN,NaN,NaN,Incomplete,Incomplete,Yes,2020-01-02,Complete
1,42.0,3.0,3.0,<=5,<50,>=40,21-49,41-50,<=12,Checked,...,0: Normal: No fluctuations or No impact by f...,0: Normal: No motor fluctuations.,0: Normal: No dystonia OR NO OFF TIME.,0.0,48.0,Unverified,Unverified,Yes,NaN,Unverified
2,NaN,17.0,NaN,NaN,NaN,NaN,NaN,NaN,Above 12,Checked,...,NaN,NaN,NaN,NaN,62.0,Unverified,Unverified,Yes,NaN,Unverified
3,16.0,15.0,19.0,>5,<50,<40,<21,<=30,Above 12,Checked,...,3: Moderate: Fluctuations impact on the perf...,2: Mild: OFF times are predictable most of th...,0: Normal: No dystonia OR NO OFF TIME.,6.0,36.0,Unverified,Unverified,Yes,NaN,Unverified
4,31.0,15.0,9.0,>5,<50,<40,21-49,31-40,Above 12,Checked,...,NaN,NaN,NaN,NaN,14.0,Unverified,Unverified,Yes,NaN,Unverified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7929,67.0,0.0,3.0,<=5,>=50,>=40,>60,61-70,<=12,Checked,...,NaN,NaN,NaN,NaN,NaN,Incomplete,Complete,Yes,2023-11-03,Complete
7930,47.0,NaN,10.0,>5,<50,>=40,21-49,41-50,NaN,Checked,...,NaN,NaN,NaN,NaN,NaN,Incomplete,Complete,Yes,2023-11-08,Complete
7931,60.0,NaN,8.0,>5,>=50,>=40,>60,51-60,NaN,Checked,...,NaN,NaN,NaN,NaN,NaN,Incomplete,Complete,Yes,2023-11-10,Complete
7932,61.0,10.0,5.0,>5,>=50,>=40,>60,61-70,<=12,Checked,...,NaN,NaN,NaN,NaN,NaN,Incomplete,Complete,Yes,2023-11-15,Complete
7933,59.0,NaN,5.0,>5,>=50,>=40,50-60,51-60,NaN,Checked,...,NaN,NaN,NaN,NaN,NaN,Incomplete,Complete,Yes,2023-11-17,Complete

In [4]:
variables_4_patients = [
    'age', 'age_at_onset', 'bmi_comp', 'total_score_for_moca', 'PD_duration', 'years_of_education', 'total_score_for_bdi'
]
lxc.descriptive_analytics(df_cases[variables_4_patients])

,age,age_at_onset,bmi_comp,total_score_for_moca,PD_duration,years_of_education,total_score_for_bdi
mean,60.498,54.237,24.254,23.675,6.152,11.425,9.988
stddev,11.320,11.813,3.639,5.533,4.966,5.307,6.769
min,18.000,10.000,12.484,0.000,0.000,0.000,0.000
max,91.000,90.000,40.375,30.000,31.000,48.000,55.000
first_Q,53.000,46.000,21.907,21.000,2.000,9.000,5.000
median,61.000,55.000,24.142,25.000,5.000,12.000,9.000
third_Q,69.000,63.000,26.446,28.000,9.000,15.000,13.000

In [5]:
# Splitting the file by 'sex'
lxc.descriptive_analytics_by_group(df_data=df_cases, variables=variables_4_patients, group_var='sex')

sex                              Female       Male
age                  mean     59.686051  60.886007
                     std      11.043762  11.431398
                     min      18.000000  18.000000
                     max      90.000000  91.000000
                     first_Q  53.000000  53.000000
                     median   60.000000  62.000000
                     third_Q  67.000000  69.000000
age_at_onset         mean     53.457102  54.608007
                     std      11.505298  11.940168
                     min      12.000000  10.000000
                     max      85.000000  90.000000
                     first_Q  46.000000  47.000000
                     median   54.000000  55.000000
                     third_Q  61.416667  63.000000
bmi_comp             mean     24.167067  24.290859
                     std       3.996703   3.468445
                     min      12.484005  13.771948
                     max      39.555556  40.374610
                     first_Q  21.366869  22.100290
                     median   23.920627  24.221453
                     third_Q  26.498797  26.421240
total_score_for_moca mean     22.782416  24.055914
                     std       6.198874   5.178564
                     min       0.000000   0.000000
                     max      30.000000  30.000000
                     first_Q  20.000000  22.000000
                     median   24.000000  25.000000
                     third_Q  27.000000  28.000000
PD_duration          mean      6.099993   6.176481
                     std       4.907312   4.993856
                     min       0.000000   0.000000
                     max      31.000000  31.000000
                     first_Q   2.000000   2.000000
                     median    5.000000   5.000000
                     third_Q   9.000000   9.000000
years_of_education   mean      9.632064  12.287982
                     std       5.765649   4.839875
                     min       0.000000   0.000000
                     max      30.000000  48.000000
                     first_Q   5.000000  10.000000
                     median   10.000000  12.000000
                     third_Q  15.000000  15.000000
total_score_for_bdi  mean     10.438727   9.773266
                     std       6.858138   6.716982
                     min       0.000000   0.000000
                     max      55.000000  47.000000
                     first_Q   6.000000   5.000000
                     median    9.000000   8.000000
                     third_Q  14.000000  13.000000

In [6]:
lxc.t_test_by_group(df_data=df_cases, variables=variables_4_patients, group_var='sex')

,age,age_at_onset,bmi_comp,total_score_for_moca,PD_duration,years_of_education,total_score_for_bdi
t_stat,4.408110,3.936721,1.302473,7.708807e+00,0.622067,2.068544e+01,-3.517196
p_val,0.000011,0.000083,0.192798,1.506699e-14,0.533917,1.916370e-92,0.000439

In [7]:
lxc.mann_whitney_by_groups(df_data=df_cases, variables=variables_4_patients, group_var='sex')

,age,age_at_onset,bmi_comp,total_score_for_moca,PD_duration,years_of_education,total_score_for_bdi
u_stat,7.278170e+06,6.441112e+06,5.260400e+06,3.270978e+06,6.134128e+06,7.523388e+06,3.500299e+06
p_val,1.375313e-06,4.127430e-05,7.877597e-03,8.134692e-11,6.474314e-01,1.788440e-77,8.617075e-05

In [8]:
crosstab_vars = [
    'zone_of_origin', 'education_level', 'agecat_1', 'agecat_2', 'pdsl', 'handedness', 'work', 'reason', 
    'nature_of_work___1', 'nature_of_work___2', 'nature_of_work___3', 'over_your_lifetime_have_yo', 
    'during_your_lifetime_did_y', 'in_your_lifetime_have_you', 'in_your_lifetime_have', 
    'have_you_ever_had_a_head_i', 'l_dopa_carbidopa', 'pramipexole', 'ropinerole', 'rasageline', 
    'selegeline', 'entacapone', 'amantadine', 'apomorphine', 'medical_history_neurologic___7', 
    'medical_history_cancer___1', 'medical_history_cancer___2', 'medical_history_cancer___3', 
    'medical_history_cancer___4', 'medical_history_metabolic___1', 'medical_history_metabolic___3', 
    'medical_history_metabolic___4', 'medical_history_cardiovasc___1', 'medical_history_cardiovasc___2', 
    'medical_history_cardiovasc___3', 'medical_history_psychologi___1', 'medical_history_psychologi___3', 
    'family_member_diagnosed_wi', 'family_member_diagnosed_wi_2', 'family_member_diagnosed', 
    'ct_head', 'mri_brain_imaging', 'datscan', 'f_dopa_pet', 'pd_surgical_treatment', 'dbs_done'
]

In [9]:
lxc.chi_squared_tests(df_data=df_cases, variables=crosstab_vars, group_var='sex')

,zone_of_origin,education_level,agecat_1,agecat_2,pdsl,handedness,work,reason,nature_of_work___1,nature_of_work___2,...,medical_history_psychologi___3,family_member_diagnosed_wi,family_member_diagnosed_wi_2,family_member_diagnosed,ct_head,mri_brain_imaging,datscan,f_dopa_pet,pd_surgical_treatment,dbs_done
chi2,7.639603,4.437409e+02,13.398247,0.0,0.022453,0.276223,1.712612e+02,11.816711,7.227573e+01,6.669419,...,22.102348,0.202184,2.988144,0.067570,0.019482,4.536974,1.750282,0.679465,4.805710,2.957200
p_val,0.105709,7.402294e-96,0.000252,1.0,0.880890,0.871001,3.923859e-39,0.000587,1.871350e-17,0.009808,...,0.000003,0.652964,0.083876,0.794909,0.888994,0.033170,0.185841,0.409771,0.028366,0.085496
dof,4.000000,3.000000e+00,1.000000,1.0,1.000000,2.000000,1.000000e+00,1.000000,1.000000e+00,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

Let us consider only the patients. Given certain tests, let us check if there are differences by sex.

In [10]:
condition = {
    'ct_head'          : 'ct_result___1',
    'mri_brain_imaging': 'mri_result___1',
    'datscan'          : 'datscan_result___1',
    'f_dopa_pet'       : 'f_dopa_pet_result___1'
}

In [11]:
lxc.chi_squared_conditioned(
    df_data=df_cases,
    conditionants=condition,
    group_var='sex'
)

           Condition               Variable      chi2     p_val  dof
0            ct_head          ct_result___1  0.167038  0.682758  1.0
1  mri_brain_imaging         mri_result___1  0.253953  0.614305  1.0
2            datscan     datscan_result___1       0.0       1.0  1.0
3         f_dopa_pet  f_dopa_pet_result___1  0.568125  0.451005  1.0

In [12]:
crosstab_vars_1 = [
    'psychiatric_symptoms_type___1', 'psychiatric_symptoms_type___2', 'psychiatric_symptoms_type___3',
    'initial_symptom_s___1', 'initial_symptom_s___2', 'inmotnonmot'
]

In [13]:
lxc.chi_squared_tests(df_data=df_cases, variables=crosstab_vars_1, group_var='sex')

,psychiatric_symptoms_type___1,psychiatric_symptoms_type___2,psychiatric_symptoms_type___3,initial_symptom_s___1,initial_symptom_s___2,inmotnonmot
chi2,1.577522,0.635101,9.020111,0.038667,0.333708,0.002219
p_val,0.209118,0.425491,0.002670,0.844109,0.563484,0.962433
dof,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [14]:
lxc.fisher_exact_test(df_data=df_cases, variables=crosstab_vars_1, group_var='sex')

,psychiatric_symptoms_type___1,psychiatric_symptoms_type___2,psychiatric_symptoms_type___3,initial_symptom_s___1,initial_symptom_s___2,inmotnonmot
fisher,1.446865,0.560346,1.414193,0.981787,1.062280,0.987375
p_val,0.164328,0.460833,0.002918,0.814654,0.527271,0.952598

In [15]:
crosstab_vars_2 = [
    'initial_motor_symptom_s___1', 'initial_motor_symptom_s___2', 'initial_motor_symptom_s___3', 
    'initial_motor_symptom_s___4', 'initial_motor_symptom_s___5', 'initial_motor_symptom_s___6', 
    'initial_motor_symptom_s___7', 'initial_motor_symptom_s___8', 'initial_motor_symptom_s___9', 
    'initial_motor_symptom_s___10', 'initial_motor_symptom_s___11', 'initial_motor_symptom_s___12', 
    'initial_motor_symptom_s___13', 'initial_motor_symptom_s___14', 'initial_motor_symptom_s___15', 
    'initial_motor_symptom_s___16', 'initial_motor_symptom_s___17'
]
lxc.chi_squared_tests(df_data=df_cases, variables=crosstab_vars_2, group_var='sex')

,initial_motor_symptom_s___1,initial_motor_symptom_s___2,initial_motor_symptom_s___3,initial_motor_symptom_s___4,initial_motor_symptom_s___5,initial_motor_symptom_s___6,initial_motor_symptom_s___7,initial_motor_symptom_s___8,initial_motor_symptom_s___9,initial_motor_symptom_s___10,initial_motor_symptom_s___11,initial_motor_symptom_s___12,initial_motor_symptom_s___13,initial_motor_symptom_s___14,initial_motor_symptom_s___15,initial_motor_symptom_s___16,initial_motor_symptom_s___17
chi2,0.006582,0.198071,0.474892,5.744484,2.359021,0.0,0.138199,0.257091,11.532923,1.900829,0.000594,1.095759,2.929418,0.0,1.594662,0.013185,1.286604
p_val,0.935340,0.656282,0.490745,0.016541,0.124560,1.0,0.710078,0.612126,0.000684,0.167986,0.980551,0.295199,0.086979,1.0,0.206661,0.908583,0.256675
dof,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.000000,1.000000

In [16]:
crosstab_vars_3 = [
    'initial_non_motor_symptom___1', 'initial_non_motor_symptom___2', 'initial_non_motor_symptom___3', 
    'initial_non_motor_symptom___4', 'initial_non_motor_symptom___5', 'initial_non_motor_symptom___6', 
    'initial_non_motor_symptom___7', 'initial_non_motor_symptom___8', 'initial_non_motor_symptom___9', 
    'initial_non_motor_symptom___10', 'initial_non_motor_symptom___11', 'initial_non_motor_symptom___12', 
    'initial_non_motor_symptom___13', 'initial_non_motor_symptom___14', 'initial_non_motor_symptom___15', 
    'initial_non_motor_symptom___16', 'initial_non_motor_symptom___17', 'initial_non_motor_symptom___18', 
    'initial_non_motor_symptom___19', 'initial_non_motor_symptom___20', 'initial_non_motor_symptom___21'
]
lxc.chi_squared_tests(df_data=df_cases, variables=crosstab_vars_3, group_var='sex')

,initial_non_motor_symptom___1,initial_non_motor_symptom___2,initial_non_motor_symptom___3,initial_non_motor_symptom___4,initial_non_motor_symptom___5,initial_non_motor_symptom___6,initial_non_motor_symptom___7,initial_non_motor_symptom___8,initial_non_motor_symptom___9,initial_non_motor_symptom___10,...,initial_non_motor_symptom___12,initial_non_motor_symptom___13,initial_non_motor_symptom___14,initial_non_motor_symptom___15,initial_non_motor_symptom___16,initial_non_motor_symptom___17,initial_non_motor_symptom___18,initial_non_motor_symptom___19,initial_non_motor_symptom___20,initial_non_motor_symptom___21
chi2,0.180094,7.087687,0.570970,0.449746,5.175372,4.551936,1.240130,0.027981,2.482981,1.943603,...,0.320831,5.050813,0.0,0.009489,0.0,1.660103,1.111585,1.012857,1.120899,0.193702
p_val,0.671293,0.007762,0.449874,0.502456,0.022909,0.032882,0.265446,0.867153,0.115084,0.163278,...,0.571109,0.024614,1.0,0.922398,1.0,0.197589,0.291738,0.314219,0.289725,0.659853
dof,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.0,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000

In [17]:
crosstab_vars_4 = [
    'current_motor_symptom_s___1', 'current_motor_symptom_s___2', 'current_motor_symptom_s___3', 
    'current_motor_symptom_s___4', 'current_motor_symptom_s___5', 'current_motor_symptom_s___6',
    'current_motor_symptom_s___7', 'current_motor_symptom_s___8', 'current_motor_symptom_s___9',
    'current_motor_symptom_s___10', 'current_motor_symptom_s___12', 'current_motor_symptom_s___13',
    'current_motor_symptom_s___14', 'current_motor_symptom_s___15', 'current_motor_symptom_s___16',
    'current_motor_symptom_s___17', 'current_motor_symptom_s___18', 'current_motor_symptom_s___19',
    'current_motor_symptom_s___20'
]
lxc.chi_squared_tests(df_data=df_cases, variables=crosstab_vars_4, group_var='sex')

,current_motor_symptom_s___1,current_motor_symptom_s___2,current_motor_symptom_s___3,current_motor_symptom_s___4,current_motor_symptom_s___5,current_motor_symptom_s___6,current_motor_symptom_s___7,current_motor_symptom_s___8,current_motor_symptom_s___9,current_motor_symptom_s___10,current_motor_symptom_s___12,current_motor_symptom_s___13,current_motor_symptom_s___14,current_motor_symptom_s___15,current_motor_symptom_s___16,current_motor_symptom_s___17,current_motor_symptom_s___18,current_motor_symptom_s___19,current_motor_symptom_s___20
chi2,0.964468,3.615509,0.591673,1.063028,9.123214,10.102853,2.693080e+01,6.761336,3.597390e+01,0.113601,0.845101,1.779878,2.050351,0.190804,6.367413,0.0,14.953476,5.431242,0.0
p_val,0.326064,0.057243,0.441773,0.302526,0.002524,0.001480,2.108717e-07,0.009315,1.999780e-09,0.736081,0.357942,0.182164,0.152171,0.662248,0.011623,1.0,0.000110,0.019780,1.0
dof,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000e+00,1.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.000000,1.0

In [18]:
crosstab_vars_5 = [
    'current_non_motor_symptom___1', 'current_non_motor_symptom___2', 'current_non_motor_symptom___3', 
    'current_non_motor_symptom___4', 'current_non_motor_symptom___5', 'current_non_motor_symptom___6', 
    'current_non_motor_symptom___7', 'current_non_motor_symptom___8', 'current_non_motor_symptom___9', 
    'current_non_motor_symptom___10', 'current_non_motor_symptom___11', 'current_non_motor_symptom___12', 
    'current_non_motor_symptom___13', 'current_non_motor_symptom___14', 'current_non_motor_symptom___15', 
    'current_non_motor_symptom___16', 'current_non_motor_symptom___17', 'current_non_motor_symptom___18', 
    'current_non_motor_symptom___19', 'current_non_motor_symptom___20', 'current_non_motor_symptom___21', 
    'current_non_motor_symptom___22', 'current_non_motor_symptom___23'
]
lxc.chi_squared_tests(df_data=df_cases, variables=crosstab_vars_5, group_var='sex')

,current_non_motor_symptom___1,current_non_motor_symptom___2,current_non_motor_symptom___3,current_non_motor_symptom___4,current_non_motor_symptom___5,current_non_motor_symptom___6,current_non_motor_symptom___7,current_non_motor_symptom___8,current_non_motor_symptom___9,current_non_motor_symptom___10,...,current_non_motor_symptom___14,current_non_motor_symptom___15,current_non_motor_symptom___16,current_non_motor_symptom___17,current_non_motor_symptom___18,current_non_motor_symptom___19,current_non_motor_symptom___20,current_non_motor_symptom___21,current_non_motor_symptom___22,current_non_motor_symptom___23
chi2,1.940712,3.669564,0.319483,0.413107,21.312168,1.839056,6.391653,0.329619,0.047270,9.127396,...,1.118034,0.370423,8.080706,3.567968,0.919833,0.0,20.029470,0.877138,7.245036,0.0
p_val,0.163591,0.055415,0.571919,0.520397,0.000004,0.175062,0.011466,0.565883,0.827883,0.002518,...,0.290342,0.542774,0.004474,0.058904,0.337519,1.0,0.000008,0.348987,0.007110,1.0
dof,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.000000,1.000000,1.0